### ISSUE TITLE
We need some starting code!

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#1]
I nominate my handsome script as a starting point! In all seriousness though, your idea of a universal config file is a good one. So if we each add our individual script and adapt it for a config maybe we can merge scripts then?

**Comment by torbengb** [comment]
You're right of course! I'm not sure it would be helpful to add all existing files here, wouldn't it become messy? How about instead if "we" (who actually? me perhaps?) look into the existing scripts and pick out the most elegant parts with which to build a new file?

There are ~30 Python scripts and ~12 Ruby and Javascript scripts, so it would be a manageable effort per language. If people want to add other languages, sure why not (I'm just using the top-3 as an example) but really our focus should be on import formats.

**Comment by nocalla** [comment]
Does any project have a decent import config file?

**Comment by torbengb** [comment]
Clearly this issue is already solved :+1:
