### ISSUE TITLE
Support for Metro Bank [UK]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#114]
Name of Bank: Metro Bank
Country: United Kingdom

Sourced from [Thau/metro-ynab-convert](https://github.com/Thau/metro-ynab-convert)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master Issue #21

**Comment by torbengb** [comment]
I've sent a message to the developer. https://github.com/Thau/metro-ynab-convert/issues/1

**Comment by torbengb** [comment]
Closing for lack of information.
