### ISSUE TITLE
Support for Barclays [UK]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#117]
Name of Bank: Barclays
Country: United Kingdom

Sourced from: [scottrobertson/barclays-to-ynab](https://github.com/scottrobertson/barclays-to-ynab)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master Issue #21

**Comment by torbengb** [comment]
I've messaged Scott for details. https://github.com/scottrobertson/barclays-to-ynab/issues/2

**Comment by torbengb** [comment]
Scott informs that Barclays is directly supported in YNAB. No need for us to support it. Closing.
