### ISSUE TITLE
Support for Deutsche Sparkasse [DE]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#118]
Name of Bank: Deutsche Sparkasse
Country: Germany

Source: [Salem5/ConvertBankstatementForYNAB](https://github.com/Salem5/ConvertBankstatementForYNAB)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
I've asked the developer, let's see if there is a response. Note that his repo hasn't changed in two years, so the chances may be slim. 

https://github.com/Salem5/ConvertBankstatementForYNAB/issues/1

**Comment by torbengb** [comment]
Closing for lack of information.
