### ISSUE TITLE
Support for Siam Commercial Bank [TH]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#119]
Name of Bank: Siam Commercial Bank
Country: Thailand

Source: [ROldford/pdf2ynab](https://github.com/ROldford/pdf2ynab)

`"DATE",
            "TIME",
            "TRANSACTION",
            "CHANNEL",
            "DESCRIPTION",
            "CHQ NO.",
            "WITHDRAWAL",
            "DEPOSIT",
            "BALANCE"`

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
I've asked the developer for a sample file: https://github.com/ROldford/pdf2ynab/issues/2

**Comment by torbengb** [comment]
"Death by timeout." Closing this issue.
