### ISSUE TITLE
Script doesn't like Umlauts: üöäÜÖÄßæøåÆØÅ

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#12]
My testing showed that the script stops at line 71 'transaction_data = list(transaction_reader)' if the file contains special characters like üöäÜÖÄßæøåÆØÅ. Shouldn't the whole Unicode business already take care of umlauts?

The error message on the console is:

    Trying format:  Raiffeisen Bank
    Parsing file:  elbi_umsaetze_20171018213618.csv
    Traceback (most recent call last):
      File "./transaction_csv_cleanup.py", line 160, in <module>
        main()
      File "./transaction_csv_cleanup.py", line 152, in main
        output = clean_data(file)
      File "./transaction_csv_cleanup.py", line 70, in clean_data
        transaction_data = list(transaction_reader)
      File "/usr/lib/python3.5/codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 3101: invalid continuation byte

When I replace all umlauts in the test file 'elbi_umsaetze_20171018213618.csv' then this error goes away.

**Workaround:** open the file in Notepad and use search&replace to remove the special characters. (Yes this sucks, we're working on it!)

**Comment by nocalla** [comment]
Might need to revert the UTF-8 encoding on read in line 26.

**Comment by torbengb** [comment]
Nope; I just changed it back to `config.read(conf_files)` but got the same error still.

**Comment by nocalla** [comment]
Try changing the encoding to latin-1. [Link](https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte )

**Comment by torbengb** [comment]
You mean encoding the *downloaded file* in Latin-1? It's a good test case. I'll check and report back.

This leads me to realize another question: Can we make the script either encoding-agnostic, or auto-detect the encoding and then either handle it accordingly or even convert the input file?

**Comment by nocalla** [comment]
Well the downloaded file is already in that encoding. We're just telling
the file reader what encoding to read it in. Change UTF-8 to latin-1 in
line 26.

I'm uncertain about auto detection of encoding. I'd imagine it's possible
but have no experience with it.

**Comment by torbengb** [comment]
> Change UTF-8 to latin-1 in line 26.
*D'oh!* :-) that's what you meant, sorry for misunderstanding. I'll test it at home.

**Comment by nocalla** [comment]
I tried this with ááááééééáá and had no problem with it.

**Comment by torbengb** [comment]
I'll have a go at it tonight and report back.

**Comment by torbengb** [comment]
Very odd! I get the above error regardless whether I have:  
`    config.read(conf_files, encoding = "latin-1")` or  
`    config.read(conf_files, encoding = "utf-8")`   
I'm testing with your _ááááééééáá_ and my _üöäÜÖÄßæøåÆØÅ_ in separate and otherwise good test cases, see attached. I'm at a loss here.

[elbi_umsaetze_20171018220326.csv.txt](https://github.com/torbengb/bank2ynab/files/1403403/elbi_umsaetze_20171018220326.csv.txt)

**Comment by nocalla** [comment]
What happens if you remove the encoding bit from the function altogether?

**Comment by nocalla** [comment]
I'm curious to see if you still get this issue now after resolving issue #29.

**Comment by torbengb** [comment]
Sorry @nocalla but I still get errors when run with Python 2:

    ('Parsing file: ', 'elbi_umsaetze_20171022210838.csv')
    ('Using format: ', u'AT Raiffeisen Bank')
    Traceback (most recent call last):
      File "bank2ynab.py", line 171, in <module>
        main()
      File "bank2ynab.py", line 163, in main
        output = clean_data(file)
      File "bank2ynab.py", line 71, in clean_data
        transaction_reader = csv.reader(transaction_file, delimiter = delim)
    TypeError: "delimiter" must be string, not unicode

This is a different error than [this one from the pull request](https://github.com/torbengb/bank2ynab/pull/26#issuecomment-338501775).

It works with Python 3!

**Comment by nocalla** [comment]
Okay great! That's the python 2 failure we're getting for delimiters. It's a separate issue to the umlauts so this issue is resolved?

**Comment by torbengb** [comment]
If you say so then yes it's resolved! :-) I guess I can close it then.
