### ISSUE TITLE
Support for TD Bank [US]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#123]
Name of Bank: TD Bank
Country: USA

Source: [RichardLitt/ynab-convert-csv](https://github.com/RichardLitt/ynab-convert-csv)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master Issue #21

**Comment by torbengb** [comment]
Config based on [this sample file](https://raw.githubusercontent.com/RichardLitt/ynab-convert-csv/master/examples/tdbank.csv)

```
[US TB Bank]
Use Regex for Filename = ????
Source Filename Pattern = ????
Source Filename Extension = .csv
Header Rows = 0
Footer Rows = 0
Input Columns = Date,skip,skip,skip,Payee,Outflow,Inflow,skip,skip,skip
Date Format = MM/DD/YYYY
```
Note that there's no inflow in the sample data! I've made the *guess* that it would be the column after Outflow, hence added as such.

**Comment by torbengb** [comment]
I've added it to the config, with the user comment as discussed.
