### ISSUE TITLE
Support for Migros Bank [CH]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#125]
Name of Bank: Migros Bank
Country: Switzerland

Source: [p-26/MigrosBankSwiftMessageParser](https://github.com/p-26/MigrosBankSwiftMessageParser)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
Closing: this one is not a CSV format but in fact a SWIFT message format. I doubt we'll get anything useful out of that!
