### ISSUE TITLE
Support for OCBC Bank [SG]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#126]
Name of Bank: OCBC Bank 
Country: Singapore [SG]

Source: [fongming/OCBC-YNAB-Parser](https://github.com/fongming/OCBC-YNAB-Parser) 

```
[SG OCBC Bank, checking and credit card]
# source: Issue #126
Use Regex for Filename = True
Source Filename Pattern = TransactionHistory_[0-9]{12}
```

Note: The source code ([direct link](https://github.com/fongming/OCBC-YNAB-Parser/blob/c3a5f9159a064d94799cfd9604213ff16af990d1/OCBC_YNAB_Parser.py#L40)) determines bank transactions or credit card based on the presence of certain words, and there seem to be different number of header rows depending on bank transactions ([here](https://github.com/fongming/OCBC-YNAB-Parser/blob/c3a5f9159a064d94799cfd9604213ff16af990d1/OCBC_YNAB_Parser.py#L12)) or credit card ([here](https://github.com/fongming/OCBC-YNAB-Parser/blob/c3a5f9159a064d94799cfd9604213ff16af990d1/OCBC_YNAB_Parser.py#L31)) - but apparently the same default filename.

Master issue #21

**Comment by torbengb** [comment]
The source is based on Python, so perhaps @nocalla wouldn't have too much trouble grokking it?

The developer has been inactive for 2 years, so if you can't figure it out, let's close this issue as `wontfix`.

**Comment by njunxuan** [comment]
Hi guys, I am interested in contributing on this issue as I do use this bank.

I have been looking at the code and based on what I gather, all that is necessary is for an appropriate conf to be created?

**Comment by nocalla** [comment]
Hi! Thanks for the comment  

@torbengb is our documentation wizard, so he can reference the right docs, but it's very straightforward to make a config to be honest. 

What I'd suggest is that you paste an anonymised chunk of your sample data here. Or fill out the survey on the front page. 

Example config below:
To be filled in as required. Delete fields that match default values.
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

**Comment by njunxuan** [comment]
Thanks for the reply! I have whipped up a config that has seemed to work but it is pretty rough. The bank format uses an additional row per transaction to include information payee information. I am not sure whether custom logic has to be included to extract this information or if there is some built in tools.

It was also necessary for me to slightly modify the code to include an additional safety check due to the additional rows. I have pushed the branch to my fork, hope you could take a look.

PS the tests are failing for me on the latest develop branch - not sure if this is due to a problem with my setup. So I am unable to test if my modifications broke anything.

**Comment by nocalla** [comment]
That does seem to do the trick. What exactly is that payee row? Is it info about the previous line?  Sorry about the comment spam on your commit - my equivalent of thinking aloud!

**Comment by torbengb** [comment]
@njunxuan we haven't completed the documentation yet, but the proper place to look would be this page:  
https://github.com/torbengb/bank2ynab/wiki/ImportFormats

I'll try to update that page with useful information about the configuration syntax!

As @nocalla suggests, you could provide a sample CSV file (please upload to the `/test-data/` directory), or [use this convenient form](https://goo.gl/forms/b7SNwTxmQFfnXlMf2) and we'll do the configuration in a few minutes.

**Comment by nocalla** [comment]
I think the config they've done is pretty good as is. The one weird thing
is the alternating rows with extra info. More info on that would help pin
down if it's worth doing a plugin for or if it can just be jettisoned.

**Comment by torbengb** [comment]
Didn't the forked code change already solve that extra-row issue? I agree that a sample file will help a lot.

Note that the [NL Rabobank-2018] format also has every other line completely blank, see [the sample file](https://github.com/torbengb/bank2ynab/blob/develop/test-data/CSV_A_20180414_112204.csv).

**Comment by njunxuan** [comment]
Hi I have added a sample CSV file to my branch. As you all can see, the "alternate row" may also include other information depending on the nature of the transaction - cash withdrawal or debit card transaction.

@torbengb the main difficulty now is that the fixed csv file will not have payee information included, which is not ideal.

**Comment by nocalla** [comment]
This is plugin territory I think. Need to pre process the file to a
"normal" CSV layout before tackling it if we want to have the payee info in
the right rows.
Is it always the same column and is it always the row after the relevant
transaction?

**Comment by torbengb** [comment]
@njunxuan Sorry but I can't find the sample CSV file you mention. Can you link it?

@nocalla I wonder if we could simply concatenate every two rows together, to create half as many rows but with the combined number of columns? But yeah, any solution must do more than simple mapping - how great that you already created a plugin platform!!

**Comment by nocalla** [comment]
[This](https://github.com/njunxuan/bank2ynab/blob/ocbc/test-data/TransactionHistory_20180418043121.csv) is the referenced file. 

```
Account details for:,FRANK Account XXX-XXXXXX-XXX
Available Balance,"XXXXX.XX"
Ledger Balance,"XXXXX.XX"

Transaction History 
Transaction date,Value date,Description,Withdrawals (SGD),Deposits (SGD)
18/04/2018,18/04/2018,DEBIT PURCHASE,X.XX,
,,15/04/18  xx-XXXX PAYEE INFORMATION
17/04/2018,17/04/2018,CASH WITHDRAWAL  ATM,XX.XX,
,,xx-XXXX PAYEE INFORMATION
```

[This](https://github.com/njunxuan/bank2ynab/blob/ocbc/bank2ynab.conf) is @njunxuan's proposed config.
```
[SG OCBC Bank]
Use Regex For Filename = True
Source Filename Pattern = TransactionHistory_\d{4}\d{2}\d{2}\d{6}
Header Rows = 6
Footer Rows = 2
Input Columns = Date,skip,Memo,Outflow,Inflow
Date Format = %%d/%%m/%%Y
```

It kinda looks like the Payee Information lines only have 3 columns vs the 5 in other rows. It also looks like the date is part of the payee name, which seems kinda unhelpful. Is the memo field the more useful field here? 

Proposed plugin action: We could do a pre-processing step that strips commas out of the Payee Info row and then dump the entirety of that row into a single "Payee" field at the end of each row. Then the Input Columns would be "Date,skip,Memo,Outflow,Inflow,Payee".

Thoughts?

**Comment by nocalla** [comment]
Adding a branch for on the main bank2ynab [here](https://github.com/torbengb/bank2ynab/tree/feature/126_Support_for_OCBC_Bank). I've merged @njunxuan's changes into that branch. 

The main modifications should be in the [OCBC_Bank_SG.py](https://github.com/torbengb/bank2ynab/blob/feature/126_Support_for_OCBC_Bank/plugins/OCBC_Bank_SG.py) plugin's _preprocess_file function.

**Comment by torbengb** [comment]
To me it looks like we could concatenate every set of two rows, and then use `Input Columns = Date,skip,skip,Outflow,Inflow,skip,skip,Memo`? We would have this concatenated data:

    Transaction date,Value date,Description,Withdrawals (SGD),Deposits (SGD)
    18/04/2018,18/04/2018,DEBIT PURCHASE,X.XX,,,15/04/18  xx-XXXX UBER EATS AN2GO HELP.UBERh 
    18/04/2018,18/04/2018,CCY CONVERSION FEE,X.XX,,,  FOR: X.XX SGD 
    17/04/2018,17/04/2018,CASH WITHDRAWAL  ATM,XX.XX,,,xx-XXXX OCBC-XXX BRANCH          S
    16/04/2018,16/04/2018,CCY CONVERSION FEE,X.XX,,,FOR: XX.XX SGD
    16/04/2018,16/04/2018,DEBIT PURCHASE,X.XX,,,xx-XXXX MCDONALD'S (BSJ8)        S 14/04/18

Based on the dummy entries, I think column 3 is not as useful for Memo as column 6?

**Comment by nocalla** [comment]
I think column 3 is a memo, i.e. a brief transaction, while the extra row
is the payee, i.e. Who the payment is to/from. So I think keep both and
concatenate. Now that we have confirmation of it always being afterwards
and always 3 columns it should be fine.

**Comment by njunxuan** [comment]
I think column 6 is generally payee information. Column 3 would be either Memo or just unnecessary I suppose. I am also thinking of ways to clean up column 6 so that its more useful as input for the payee column.

I'll try to provide a fuller test file tomorrow.

**Comment by torbengb** [comment]
@njunxuan I don't mean to hurry you, but please don't forget about the test file. Thank you!

**Comment by nocalla** [comment]
What's wrong with the test file?

**Comment by torbengb** [comment]
The file is okay after you put in all those 6'es - but I think Jun wanted
to add "real" data instead?

**Comment by njunxuan** [comment]
Is it necessary for the file to have "real" data? If it is then I'll provide one!

**Comment by nocalla** [comment]
I wouldn't have said so - the file has an amount of transactions sufficient for us to see what we want from it.

**Comment by njunxuan** [comment]
In that case I'll just leave it as it is then. Thanks for all the help :)
