### ISSUE TITLE
Support for Royal Bank of Scotland [UK]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#127]
Name of Bank: Royal Bank of Scotland
Country: United Kingdom

Source: [jcalero/ynab-rbs-converter](https://github.com/jcalero/ynab-rbs-converter)

```
$rbs_headers = [
	'date' => 'Date',
	'type' => 'Type',
	'description' => 'Description',
	'value' => 'Value',
	'balance' => 'Balance',
	'account-name' => 'Account Name',
	'account-number' => 'Account Number'
];
```

```
[UK Royal Bank of Scotland]
# source: Issue #127
Input Columns = Date,skip,Payee,Inflow,skip,skip,skip
```

Master issue #21

**Comment by torbengb** [comment]
I've asked the developer, let's see if he responds.

https://github.com/jcalero/ynab-rbs-converter/issues/1

**Comment by torbengb** [comment]
Added a reminder to the developer's ticket.

**Comment by torbengb** [comment]
"Death by timeout." Closing this issue.
