### ISSUE TITLE
Support for UBS [CH]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#128]
Name of Bank: UBS
Country: Switzerland [CH]

Source: [fahyik/UBS_YNAB](https://github.com/fahyik/UBS_YNAB)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
Updated the issue in the developer's repo: https://github.com/fahyik/UBS_YNAB/issues/1
Chances of a response seem slim, as we didn't get a response on the original issue either. 

https://github.com/fahyik/UBS_YNAB/issues/1

**Comment by torbengb** [comment]
Closing for lack of information.
