### ISSUE TITLE
Support for DNB [NO]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#129]
Name of Bank: DNB
Country: Norway [NO]

Source: [cronin101/DNB-2-YNAB-CSVConverter](https://github.com/cronin101/DNB-2-YNAB-CSVConverter)

**To be filled in as required. Delete fields that match default values.**
Use Regex For Filename = True
Source Filename Pattern = maanedtransaksjonliste-[a-z]{3}
Source CSV Delimiter = ;
Input Columns = Date,Payee,skip,Outflow,Inflow

Master issue #21

**Comment by nocalla** [comment]
Aha, there's an updated version of this project living online [here](http://cronin101.github.io/DNB2YNAB-TypeScript/) which lists out our column headers!

`"Date";"Description";"Interest date";"Withdrawals";"Deposits"
"01.02.2003";"Example Income";"01.02.2003";"";"49,534.96"
"01.02.2003";"Example Outgoing Payment";"01.02.2003";"2,490.00";""`

**Comment by nocalla** [comment]
The only thing we're missing is the filename pattern now, I think.

**Comment by torbengb** [comment]
Good work! I'd say go ahead and build that config section - I'd rather have something (nearly?) complete than having it sit only in an issue ticket :)

**Comment by nocalla** [comment]
Done and closed.
