### ISSUE TITLE
Support for Alelo [BR]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#130]
Name of Bank: Alelo
Country: Brazil [BR]

Source: [figueredo/bank2ynab](https://github.com/figueredo/bank2ynab)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
I've asked the developer for a sample file: https://github.com/figueredo/bank2ynab/issues/1

**Comment by torbengb** [comment]
Added a reminder on the developer's ticket.

**Comment by torbengb** [comment]
Original developer states that this bank does not offer an export function; that is why he has do to copy&paste from the banking website. 

Because of this, I don't see a reliable way for `bank2ynab` to handle this bank, so I am sadly closing this issue.
