### ISSUE TITLE
Support for Deutschebank [DE]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#131]
Name of Bank: Deutschebank
Country: Germany [DE]

Source: [marfei/db-to-ynab](https://github.com/marfei/db-to-ynab) and [milenvoutchev/db2ynab](https://github.com/milenvoutchev/db2ynab/blob/master/samples/DbCreditCard.csv)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Header Rows = 5
Footer Rows = 1
Source CSV Delimiter = ;
Input Columns = Date,skip,skip,skip,skip,skip,Inflow,skip
Plugin =

Master issue #21

**Comment by torbengb** [comment]
I've now [asked the developer](https://github.com/marfei/db-to-ynab/issues/1) for details, but I'm not sure he will reply. Let's see!

**Comment by torbengb** [comment]
Updated format based on [milenvoutchev/db2ynab](https://github.com/milenvoutchev/db2ynab/blob/master/samples/DbCreditCard.csv)

**Comment by torbengb** [comment]
Added without filename for now. I'll keep the issue open for a while, waiting for "milenvoutchev" to respond to the question.

**Comment by torbengb** [comment]
Reminded the developer about the default file name. Not giving up just yet :)

**Comment by torbengb** [comment]
Okay, timeout, I am closing this format issue.
