### ISSUE TITLE
Support for Finnish Osuuspankki [FI]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#133]
Name of Bank: Finnish Osuuspankki
Country: Finland [FI]

Source: [mixu-/ynab-csv](https://github.com/mixu-/ynab-csv) [Python]

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ;
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by nocalla** [comment]
The listed project only lists the field names of the import file, but doesn't specify their order.

**Comment by torbengb** [comment]
I saw you updated the ticket on his project. I also just pinged him on LinkedIn because I'm not sure he'd see it otherwise.

**Comment by torbengb** [comment]
Closing for lack of information.
