### ISSUE TITLE
Support for Swedbank [SE] 

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#134]
Name of Bank: Swedbank
Country: Sweden [SE] 

Source: [jpsk/Swedbank-to-YNAB4-converter](https://github.com/jpsk/Swedbank-to-YNAB4-converter)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
I believe I have completed this. Closing.
