### ISSUE TITLE
Support for N26 [DE] 

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#137]
Name of Bank: N26
Country: Germany [DE]

Source: [DarkSmile92/YNABConverterPy](https://github.com/DarkSmile92/YNABConverterPy)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by diarmuidbourke** [comment]
I've made a patch to add support here: https://github.com/torbengb/bank2ynab/pull/149

**Comment by nocalla** [comment]
Thanks for the input, @diarmuidbourke - as I mentioned on the pull request, the combined Inflow/Outflow is already accounted for, so there's no need to change the code for this bank - just the config file .

So, I've had a look at our survey and it looks like the config format should be as below. I've included the raw paste from the survey data too. I took the regex pattern from your pull request's code. Can you try this config with the main branch and see if it works?

```
[DE N26]
Source Filename Pattern = [0-9]{8}-[0-9]{8}
Input Columns = Date,Payee,skip,skip,Memo,skip,Inflow
```

Survey Data:
11/6/2017 15:18:17 | DE | N26 | Checking and MasterCard | Comma | Yes | Datum,Empfänger,Kontonummer,Transaktionstyp,Verwendungszweck,Kategorie,Betrag (EUR),Betrag (Fremdwährung),Fremdwährung,Wechselkurs | 2017-10-01,NINTENDO OF EUROPE,,MasterCard Zahlung,,Medien & Elektronik,-59.99,-59.99,EUR,1.0 | Date | Payee |   |   | Memo |   | Amount (EUR) (outflow: <0 inflow: >0) |   |   |   |   |   |   |   |   |   |   |   |   |   | robin@rkmail.email / https://github.com/DarkSmile92 | Reddit: DarkSmile92 |   | 20171001-20171106.csv |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by torbengb** [comment]
I believe I have completed this. Closing.
