### ISSUE TITLE
Support for Shopify [E-Commerce Platform]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#139]
Name of Bank: Shopify
E-Commerce Platform

Source: [rennes-us/ynab-convert](https://github.com/rennes-us/ynab-convert)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
This is as much as I've been able to determine so far. To be edited as I learn more:
```
[US Shopify transactions]
Source Filename Pattern = payment_transactions_export

[US Shopify payouts]
Source Filename Pattern = payouts_export
```

**Comment by nocalla** [comment]
Agreed.
