### ISSUE TITLE
Rename filenames to match project name?

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#14]
Would it be helpful to rename the script from `transaction_csv_cleanup.py` to `bank2ynab.py`, and the config file from `config.conf` to `bank2ynab.conf`?

I believe it would help "the project" because it creates a direct correlation between the project name and the script name (like MS Excel is also called `excel.exe`). It would also be handy because users (me!) could put the script and config in the user-home directory or anywhere else that is already in the `path`, and avoid having to `cd` to the script location first or precede the command with the script path.

If you agree I could do the simple pull, but these are your file names so I don't want to steamroll over your choices, hence this question for your consideration.

**Comment by nocalla** [comment]
Makes sense. I've no problem with the name change.
