### ISSUE TITLE
Support for Consorsbank [DE] 

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#141]
Name of Bank: Consorsbank
Country: Germany [DE] 

Source: [nicolaipischel/YnabBankDataConverter](https://github.com/nicolaipischel/YnabBankDataConverter) [C#]

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
Closing this issue because the source project has been deleted. We have no data to build on.
