### ISSUE TITLE
Support for KSK [DE]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#145]
Name of Bank: KSK - not sure which one exactly! Need translation help. Edit when this is known!
Country: Germany [DE]

Source: [Bockwurst2/ynab_csv](https://github.com/Bockwurst2/ynab_csv)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by nocalla** [comment]
Hey @torbengb, I need some help translating the listed source to establish the actual bank apart from the initials! All the comments are in German, so I can't translate!

**Comment by torbengb** [comment]
ksk.csv, translated:

    "Book date";"Purpose";"Payee";"Account number";"Bank code";"Amount";"Currency";"Info"
    "13.04";"08.04/21.39 Foo Shop";"GA NR000041238 BLZ43059991 3";"";"43059991";"-30";"Dollar";"Transaction booked"
    "02.04";"31.03/16.38 SPK.Foo G90 EUR00000020,00";"GA NR00001147 BLZ44050199 3";"9000411008";"44050199";"-20";"Dollar";"Transaction booked"
    "01.04";"UNTERHALT";"Foo, Bar";"123456789";"43059991";"18";"Dollar";"Transaction booked"

Hope this helps?

**Comment by torbengb** [comment]
I've now [asked the developer](https://github.com/Bockwurst2/ynab_csv/issues/1) for details, but I'm not expecting a reply because his project hasn't been touched for 2+ years.

**Comment by torbengb** [comment]
Added the basic section including input columns. Source filename pattern is still undetermined.

**Comment by torbengb** [comment]
The [author states](https://github.com/Bockwurst2/ynab_csv/issues/1#issuecomment-362795361) that he never finished it and uses someone else's PHP script instead. I couldn't get useful details.

I suggest we scrap this format.
