### ISSUE TITLE
Add config parameters for header and footer lines to skip

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#153]
@nocalla [had the idea](https://github.com/torbengb/bank2ynab/issues/140#issuecomment-359944921) to include a Start and End row feature in order to be able to ignore superfluous rows outside the main body of the input CSV.

As we're already skipping the first line when there is a header, perhaps we can re-work the `Source Has Column Headers` into something like `Skip header lines = 0` and `Skip footer lines = 0` where the values would be greater than zero if a header/footer is present.

We need to make sure that blank footer lines aren't counted, though. Blank header lines should probably be counted.

**Comment by nocalla** [comment]
I was thinking more like adding two parameters "Start Line" and "End Line" to the config. With default of 0 and...hmm, I assume -1 would work - I'll have to check that.

**Comment by torbengb** [comment]
What would a negative value mean? 

Naming is important... "Start line" seems to specify at what line the real content starts? Then how would I figure out "End line"? I don't think that's what you meant?

**Comment by nocalla** [comment]
That is indeed what I meant. But you're right, end line is where it gets
messy. -1 is how you specify the last element of a list, generally, but I'm
not sure if it'd work with the csv reader.

**Comment by torbengb** [comment]
-1 means "last element"? I didn't know that. What if there is more than 1 footer row, do you specify -2? It doesn't strike me as intuitive (as a non-developer!). If you don't mind, I'd prefer my suggestions because I feel they are more descriptive.

**Comment by nocalla** [comment]
Yup, -2 is the 2nd last element. I'll have a look at different ways of
doing it and see what happens.

**Comment by nocalla** [comment]
I used the below as means of coding this. It does indeed use the negative number syntax for counting from the end of a list, but tucks it out of sight of the user. 
`output_data = output_data[header_rows:-footer_rows or None]`

**Comment by torbengb** [comment]
That is an elegant solution to our talk above, and I agree with the names you gave the parameters.

**Comment by nocalla** [comment]
As an interesting tidbit - the "or None" bit at the end means that "-0" is translated to "just ignore this and carry on to the end of the list", instead of wiping the whole list or something unpleasant like that.
