### ISSUE TITLE
Standard approach to using a credit-debit flag

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#161]
[Issue 91](https://github.com/torbengb/bank2ynab/issues/91#issuecomment-362253461) discussed that the credit-debit flag is coming up often enough that it warrants incorporation or a more general plugin. 

The general issue here is that some banking formats don't have one inflow column and one outflow column, and they also don't have one amount column where outflows are represented using negative amounts. Instead, several banks use a format where one column contains an amount (always positive) and another column contains some value to indicate whether that amount is an inflow or outflow. 

This issue is created as a task to figure out a solution to this instead of having to create a format-specific plugin _just_ for that common functionality. (Until then, format-specific plugins are a viable solution.)

This ticket needs to deal with two aspects:

1. How should the "amount" column be referenced? -- We might just use the "inflow" here for simplicity, or invent a new "amount" parameter to clearly distinguish it from normal inflows.
1. How should the "c-d flag" column be specified? -- We would need a config parameter to turn on this c-d handling in the first place. We also need parameters to specify the actual values that indicate credit and debit (because some formats helpfully use C and D but others cryptically use A and B, and other values are sure to pop up later).

**Comment by nocalla** [comment]
I reckon this can just be incorporated into the main code reasonably
easily.

1. I'd suggest using "Inflow" to reference the amount, since we know that
YNAB can handle negative Inflows.
2. I'd suggest using a config parameter like "Inflow or Outflow Flags =
Apple, Banana". This keeps it to a single parameter and is reasonably
clear. If there are no specified flags, this parameter would be ignored,
otherwise everything flagged as "Banana" is just multiplied by -1.

**Comment by torbengb** [comment]
As for aspect 2 above, I've tried to think of a compact solution that requires a minimum of new config parameters. The best I can come up with is **2 new parameters:** 

- `Credit debit flag column` to specify the column number that contains the c-d flag. The default would be zero or null, indicating that this feature is not triggered.
- `Credit debit indicator` to specify the actual value provided to indicate "credit" and "debit". As you suggest, expect two comma-separated words (any whitespace gets ignored).

Going further, we could use one parameter for the flag column as well: `Credit debit indicator = 5, Apple, Banana` as long as we are clear whether we count from 0 or 1? When this parameter is undefined (null) then the functionality is off.

**Comment by nocalla** [comment]
I like that format. Since the rest of the code counts from 0 at every opportunity, I'd stick with that. One point I disagree on though is the name - I think we should name it according to the YNAB output, i.e. something like the following:

`Inflow or Outflow Indicator = 5, Apple, Banana`

**Comment by nocalla** [comment]
[Here](https://github.com/torbengb/bank2ynab/tree/feature/161_inflow_outflow_flag) is a feature branch.

**Comment by torbengb** [comment]
You are fast! How can you be so fast? Nice job! I just looked at the code changes and it looks like you're not actually needing the `inflow_flag`? All you need is the flag column and the outflow indicator value. 

So should we decide on dropping the inflow flag? I can't realistically imagine any situation where it would be needed.

**Comment by nocalla** [comment]
I feel like it's a good idea to keep it. Just out of superstition more than anything else.

**Comment by nocalla** [comment]
And I'm fast because it's my day off and I'm trying to clear my mind of work-related things. :-)

**Comment by torbengb** [comment]
And you choose to spend your day off on Github? Commendable! :-)

**Comment by nocalla** [comment]
On the computer, the email alerts remind me to come back. :-)

**Comment by torbengb** [comment]
Hey I just realized -- do you think we can get rid of the `swedebank` plugin now? I just added a commit of the config file where I added the Outflow Indicator but I didn't remove the `plugin` parameter yet. I think I should!

**Comment by nocalla** [comment]
I don't think so - there's a line about filtering out some kind of subtotal
row too.

**Comment by torbengb** [comment]
Err... no? I don't see any subtotal in the [sample input for Swedbank](https://raw.githubusercontent.com/jpsk/Swedbank-to-YNAB4-converter/master/statement.csv).

**Comment by torbengb** [comment]
I stand corrected! There's an opening balance line right after the header line, and closing balance line at the end. How nice that we have implemented a config for that already! I'll test and report back soon.

**Comment by torbengb** [comment]
I've now committed the fixed config to the branch. It works in Py3 but not in Py2!
