### ISSUE TITLE
What can we do about all our "almost-complete" formats where we only miss the default export filename?

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#173]
We have a number of formats ready for inclusion in the configuration, **_except_** that we're missing the default export filename for each one. 

I've submitted an issue to the source repo in most of these cases, but sometimes we don't hear back. 

We could include the format in the config without a proper filename, but that won't help us much. Sure, users that have that format could perhaps add the filename themselves, but we likely won't get that feedback. Better to not include the formats in the config yet?

**Comment by nocalla** [comment]
There's arguments to be made for both sides. Could include with a comment
to submit the default file name?

**Comment by torbengb** [comment]
> submit the default file name

That could work. So instead of `Source Filename Pattern = example_transaction_export_filename`, we could call it something like `Source Filename Pattern = unknown--please-submit-an-issue-if-you-know-this`?

**Comment by nocalla** [comment]
Yup. I'd say just put it as an actual comment like: # default filename is
unknown, please submit an issue if you know the name

**Comment by torbengb** [comment]
Good idea! So obvious, too. I will also include a direct link to the new-issue page, or perhaps to a new wiki page where we say thanks and explain what we ask of the user.

**Comment by nocalla** [comment]
The link is a good idea.

**Comment by torbengb** [comment]
```
Source Filename Pattern = unknown!
# The default filename is unknown! Please submit an issue if you know the name! See details here:
# https://github.com/torbengb/bank2ynab/wiki/MissingDefaultFilename
```

**Comment by nocalla** [comment]
Perfect.

**Comment by nocalla** [comment]
Why is this issue still open? Surely we don't need to keep it open now that we've decided.

**Comment by torbengb** [comment]
I agree. Closing.
