### ISSUE TITLE
%%y-%%m-%%d causes "ValueError" in Python 2

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#174]
Script language: Python 2.7
Operating system: MacOS X

What did you DO? (steps to reproduce)
[SE Nordea] using the date format `%%y-%%m-%%d` works with Python 3, but fails on Python 2.7.

What did you EXPECT to happen?
Should work with same format specification, regardless of Python version.

Can you provide other helpful information?
Described [here in Swedish](https://github.com/davols/nordea-ynab-convert/issues/1#issuecomment-367332527) (sorry!)  
For Python 2.7, the format needs to be `%y-%m-%d`.

**Comment by nocalla** [comment]
Hmm. Does rabo bring the same error?

**Comment by torbengb** [comment]
Haven't tried yet; this report came from Sweden and not from myself. Needs testing.

**Comment by nocalla** [comment]
After a cursory search, it looks like the solution is to use the "raw" version of Configparser, but I'm not sure if this will add more complications, so I'll have to do some testing. Also, this is an issue that Travis should be able to pick up on with more comprehensive tests as per #178.

**Comment by nocalla** [comment]
I switched to the RawConfigParser function in the #203 branch if you could test it out, @torbengb. I don't *think* it breaks any normal functionality...

**Comment by torbengb** [comment]
Thank you, I will test and report back!

**Comment by nocalla** [comment]
Hmm. It's weird that it works with some banks, but not others. What's so special about BOI that makes it work?

**Comment by torbengb** [comment]
D'oh! Okay, I'll adjust the config and redo my testing. Thanks for looking into this. Will report back soonish!

**Comment by nocalla** [comment]
I've merged, so maybe adjust the test files to match the reported configs.
