### ISSUE TITLE
Projects, milestones, and how we work together

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#175]
Based on comments in #170, we should address this separate from code-specific issues. (See also #88 about branching strategy and #147 about the GitHub "projects" feature.) 

I find it odd that "projects" have their own "tab" at the top of every page, while "milestones" don't - but issues can be assigned to both projects and milestones:

- "Projects" are found in the top tabs:
   - [the page](https://github.com/torbengb/bank2ynab/projects) shows a list of projects with a progress bar for each. 
   - Clicking on one takes us to [a Kanban board](https://github.com/torbengb/bank2ynab/projects/2).
- "Milestones" are found in the page "Issues" > button "Milestones":
   - [the page](https://github.com/torbengb/bank2ynab/milestones) shows a list of milestones with a progress bar for each. 
   - Clicking on one takes us to [a list of open&closed issues](https://github.com/torbengb/bank2ynab/milestone/3) tagged for that milestone.

They're *almost* the same! I added this issue to both, just to see what happens.

What could we use "projects" for? Do we need them?
What could we use "milestones" for? Do we need them?

**Comment by nocalla** [comment]
I think we could use projects for longer goals, milestones for shorter
sprints? Or vice versa!

**Comment by nocalla** [comment]
I think they should actually sync up now that the project boards are active, as exhibited by the automation comments above...

**Comment by torbengb** [comment]
I don't think they'll sync, to be honest. It seems that projects and milestones are completely separate from each other, it's just that I happened to name them the same, and assign both. 

The automation is only inside the Kanban - when an issue gets assigned to a project, the automation figures out what column it needs to go into.

**Comment by nocalla** [comment]
I suggest we just use Projects and forget about milestones. Projects has
more features and seems to be more front-and-centre to see.

**Comment by torbengb** [comment]
Fair enough. I'll go through the project and assign everything to a reasonable project, and remove everything about milestones. This is all meta work, so no branching required.

**Comment by torbengb** [comment]
While doing this, an idea came up:

Should we perhaps change our projects from being aimed at specific release numbers, to being aimed at a general roadmap? We could have (rename) projects like:

- next MINOR release (includes bug fixes)
- later MINOR release (for new features we want to do, but not immediately)
- next MAJOR release
- later MAJOR release

Thoughts?

**Comment by torbengb** [comment]
Nevermind that idea; I created a Kanban column "Candidates" instead. Anything that doesn't get moved into "To Do" just remains there until the release is done, and can be picked up in the next iteration.
