### ISSUE TITLE
Make test suite more comprehensive

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#178]
As outlined in issue #177, our code coverage needs to improve. 

As well as satisfying a comprehensive "all lines triggered" approach, I had been meaning to add some more tests to ensure that our output is YNAB-comprehensible.

**Comment by torbengb** [comment]
I agree - now that I've seen the code coverage, I also had the idea to add/modify the test data to get through more lines. I'll try to help you with this.

**Comment by nocalla** [comment]
A good article on unit testing here:
https://jeffknupp.com/blog/2013/12/09/improve-your-python-understanding-unit-testing/

Also a discussion in the various answers here of why code coverage does not
equate to code quality:
https://stackoverflow.com/questions/3322123/ensuring-code-coverage-in-unit-testing

We do have some very specific tests at the moment, but I propose we aim to
test each function separately.

On 24 Feb 2018 07:17, "Torben Gundtofte-Bruun" <notifications@github.com>
wrote:

I agree - now that I've seen the code coverage, I also had the idea to
add/modify the test data to get through more lines. I'll try to help you
with this.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/torbengb/bank2ynab/issues/178#issuecomment-368207099>,
or mute the thread

**Comment by torbengb** [comment]
Thank you very much, this is really useful!

**Comment by torbengb** [comment]
I have added CSV files for all the formats that we have a complete spec on! (based on the survey)
I have not integrated them into the test data scripts yet.

**Comment by nocalla** [comment]
Working on this over here: https://github.com/torbengb/bank2ynab/tree/feature/178_improve_test_coverage
