### ISSUE TITLE
Push transactions into YNAB programmatically

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#18]
Scott Robertson has a method to push transactions into YNAB programmatically. 

- Can we incorporate that into our script, in order to eliminate the manual step of drag-and-dropping the output CSV file?

If we can do that, we could all but automate the entire process, like he has done. Manually donwload a CSV file (possibly automate this later, for US/UK), then run `bank2ynab` which then auto-converts, auto-imports, and removes the original CSV and the converted CSV file. 

source: https://github.com/scottrobertson/fintech-to-ynab#csv-imports: 

> You can import a CSV directly into YNAB via the CLI. To do so, please use the following:
> python python/import.py --account=AccountName --path=/path/to.csv
> The format should be: date, description, amount

**Comment by torbengb** [comment]
Need to grab this from the original source https://github.com/rienafairefr/pynYNAB 
They have a permissive MIT License just like we do, so no problems there.

**Comment by nocalla** [comment]
That's an interesting one. I'd be keen on that. I think we should clear up existing issues with the current core functionality first before going down this road though.

**Comment by torbengb** [comment]
Definitely for a future release. I haven't even begun thinking about version numbers or releases here, but that would qualify for a 2.0 bump. Are we at 0.3 right now? Also, I'd be concerned that it would be a major increase in work to implement and maintain this project. But cool? Yes. Do I want it? Certainly! Can I do this? Nope. Let's put it on the back burner for now.

Hey you know what, I just typed `2.0` into the milestone selector and presto, we now have a milestone :-p

**Comment by torbengb** [comment]
We can do this with the new YNAB API! 

See  #183. That one is assigned to v2.0 so I will also move this #18 to v2.0.

**Comment by nocalla** [comment]
I feel more like #183 is where we want to go with this. Closing this issue.
