### ISSUE TITLE
Separate master content from dev stuff

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#187]
* Our development trunk needs a lot of files for testing and so on, and these need to be under revision control so they are distributed to all contributors. This is fine. 
* Our master branch needs to have the same files so Travis can test that, too. This is fine. 
* Our release **should not** have "all that extra stuff", but it does. **This is not okay.**

--> How do we separate master content from dev stuff? How do we make the release contain *just* the program, the config, and the plugins?

Files needed in the release:
```
bank2ynab.py
bank2ynab.conf
bank2ynab.bat
LICENSE
README.md
plugins/handelsbanken.py
```
Files **not** needed in the release:
```
.coveragerc
.gitignore
.codeclimateyml
.travis.yml
docs/*
test/*
test-data/*
.......?
```

**Comment by nocalla** [comment]
Hmm. That's an interesting one. A separate "release" branch? Using got submodules for testing? How do other projects handle it?

**Comment by torbengb** [comment]
I asked the greater community here: https://softwareengineering.stackexchange.com/questions/366771/how-do-we-avoid-development-files-in-the-release

**Comment by torbengb** [comment]
> How do other projects handle it?

They have a build script (see our #176) and they understand (which I didn't until now) that _the source code are not the deliverables!_ So when we have created our packaging process, we should attach that "compiled" package to [the release](https://github.com/torbengb/bank2ynab/releases).

https://softwareengineering.stackexchange.com/a/366773/2228

**Comment by torbengb** [comment]
I have updated [the wiki page about publishing releases](https://github.com/torbengb/bank2ynab/wiki/PublishRelease) with steps 5 and 10 to reflect the above.

We now know that we need to complete #176. That answers this issue, so I will close it.
