### ISSUE TITLE
script stops if CSV file ends with newline

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#19]
My testing showed that the script stops if the imported CSV file ends with a newline.

**Workaround:** remove the trailing Enter.

**Comment by nocalla** [comment]
What error does this give?

**Comment by torbengb** [comment]
This is with a test file that has 4 good rows ending with an Enter:

    Trying format:  AT Raiffeisen Bank
    Parsing file:  elbi_umsaetze_20171018220326.csv
    Traceback (most recent call last):
      File "bank2ynab.py", line 161, in <module>
        main()
      File "bank2ynab.py", line 153, in main
        output = clean_data(file)
      File "bank2ynab.py", line 77, in clean_data
        output_data.append(fix_row(row))
      File "bank2ynab.py", line 95, in fix_row
        cell = row[index]
    IndexError: list index out of range

**Comment by nocalla** [comment]
I think I know what to try here. Better exception handling. (this comment is a reminder to myself what to try!)

**Comment by nocalla** [comment]
Note: newline treated as new row with single cell. Obviously can't find index greater than 1, hence out of range error when it looks for each column.
