### ISSUE TITLE
Determine category of a transaction based on previous transactions for same payee

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#192]
Getting inspired by other projects again :)

If we are going to do uploads, that means we have a live connection to nYNAB. We can use that to determine the category of each new transaction based on the most recent transaction for the same payee - this is basically what YNAB itself does, too.

For reference, [here is their issue about it](https://github.com/scottrobertson/fintech-to-ynab/issues/12) and [here is their code change (Ruby)](https://github.com/scottrobertson/fintech-to-ynab/commit/484f4e81f11afc518f7ad46139c7f026b9cdbea2).

Clearly something to work on "later", so tagging for v2.0 for now.

Workaround: manually assign a category after import.

**Comment by nocalla** [comment]
Is this essentially a duplicate of #30?

**Comment by torbengb** [comment]
I wrote both. I agree they are related, but I feel they are distinct:  
#192 is about grabbing the most recently assigned category directly from YNAB (so, tight integration).  
#30 is about adding a user config to `bank2ynab` that does this, independently of what's in YNAB.

I think #192 is more elegant but requires more (a functioning YNAB connection), while #30 offers more control but might require more coding (and more regex in the user config!).

I'm voting to keep both variants open until we decide on either one, then close the other.

**Comment by nocalla** [comment]
Once again, this is a duplicate of existing YNAB functionality - I think this actually is default behaviour for each payee.

**Comment by nocalla** [comment]
What do you think, @torbengb?

**Comment by torbengb** [comment]
Well, it's sort of duplicate but sort of isn't: How do you feel about importing categories into YNAB, if the categories were somehow known? Would that be 100% useful or how often would that not be useful to you?

My take is that when I import my converted CSV's into YNAB, they end up with blank payee and category columns. That's okay for payees because my banks only provide the memo column (and I could switch it into payee if I wanted, either in our config or in the YNAB import dialog).

But the bank export doesn't contain any information about categories, so after importing in YNAB I always need to go through every single transaction and fill in the category by hand. It would be nice if the CSV already contained the correct category, and that's what these two ideas aim at.

**Comment by torbengb** [comment]
> use YNAB's automatic rules to rename the payee
Well damn - I never used that, and it looks like just the thing!! I have to clean up my payees and set up some rules, but on the whole, that's what I wanted to get. 

I'll close both issues #192 and #30!
