### ISSUE TITLE
Rabobank NL format change starting 01-09-2018

### ISSUE THREAD

**Issue by jorismathijssen** [torbengb/bank2ynab#195]
# Bank Format Addition
Name of Bank: Rabobank NL
Country: Netherlands
Special Requirements:
The old file was "Transaction.txt" the .txt files will be deprecated at 01-09-2018.

```
Source Filename Pattern = CSV_A_datetime in format: {YYYYMMDD_HHMMSS} for example: CSV_A_2018_03_31_000710.csv for a file downloaded at 00:07:10 at 31 march 2018
Source Filename Extension = .csv
Use Regex for Filename = True
Source CSV Delimiter = ,
Header Rows = 1
Footer Rows = 0
Date Format = YYYY-MM-dd
```

**Comment by nocalla** [comment]
@torbengb I see you're doing something about this in commits, so I've assigned you.

**Comment by toyg** [comment]
There is a typo. The rule should be:
Source Filename Pattern = CSV_A_20[0-9]{6}_[0-9]{6}
In the current bank2ynab.conf, that last _ is actually a -
