### ISSUE TITLE
Readme.md badges broken for "GitHub issues by-label", "GitHub open issues", "GitHub last commit"

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#197]
The above badges are showing as broken image links on the main project page. 

**Relevant code:**
```
Development: 
[![GitHub issues by-label](https://img.shields.io/github/issues-raw/torbengb/bank2ynab/bug.svg)](https://github.com/torbengb/bank2ynab/issues?q=is%3Aissue+is%3Aopen+label%3Abug)
[![GitHub open issues](https://img.shields.io/github/issues-raw/torbengb/bank2ynab.svg)](https://github.com/torbengb/bank2ynab/issues)
[![GitHub last commit](https://img.shields.io/github/last-commit/torbengb/bank2ynab.svg)](https://github.com/torbengb/bank2ynab/commits/develop)
[![Join the chat at https://gitter.im/bank2ynab/Lobby](https://badges.gitter.im/github-release-notes/Lobby.svg)](https://gitter.im/bank2ynab/Lobby)
```

**Comment by nocalla** [comment]
I don't know why this is the case - I can visit the link to the images directly.

**Comment by torbengb** [comment]
Yeah, I noticed that too. I think the "shields.io" server is overloaded, so it is not always delivering all badges. You'll notice that only the badges that are served from shields.io have this problem.

Suggested solution: implement the ostrich algorithm.

**Comment by nocalla** [comment]
The ostrich algorithm has worked - the badges are showing up as normal again.
