### ISSUE TITLE
Integration into the YNAB Toolkit?

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#22]
Based on [this reddit comment](https://www.reddit.com/r/ynab/comments/77d7rt/tools_bank2ynab_heres_a_script_that_helps_with/dokwqir/), perhaps our code could be integrated into the YNAB Toolkit? That would be cool! Our project needs more supported formats first, and it would require some adaptations.

**Comment by nocalla** [comment]
That would be cool, but again - walk before we run!

**Comment by torbengb** [comment]
I didn't start this fire :-) the toolkit guy opened the topic. I am just keeping this as a reminder to come back to it later. Note the assigned milestone :-)

**Comment by nocalla** [comment]
Ah okay. Sorry, that didn't show up via email.

**Comment by nocalla** [comment]
On a side note, I installed this extension last night and was very impressed! Cleans up a lot of UI annoyances.

**Comment by torbengb** [comment]
You hadn't tried the YNAB Toolkit before? You'll like it! I have set mine up to provide a much more compact view, to see more rows on the screen at once (I dislike whitespace), and I've also turned on goal display. There are so many useful settings, really adds value to the app. And I like that the app itself doesn't have all that configuration; would be scary for new users.

**Comment by nocalla** [comment]
I'm pretty sure this is a non-starter. I queried the dev on reddit about how we'd go about integrating it in and they said the [following](https://www.reddit.com/r/ynab/comments/77d7rt/tools_bank2ynab_heres_a_script_that_helps_with/dp2nul8/?context=3).

> Main thing is that this tool is written in Python. While we use Python currently as part of the build process in Toolkit, the only way to make it actually run in the browser is to build it in Javascript.

So this is definitely not a 2.0 milestone as it would require a full rewrite. Plus I don't think it's feasible to work with the multiple configs etc and the toolkit from a user perspective. I think the better option is to do programmatic pushing of the completed csv files to YNAB as a separate workflow to the toolkit (#18).

**Comment by torbengb** [comment]
Javascript, eh? I agree, that's a completely different project. I'll close this issue and let's just see about #18 instead. Thanks for investigating!
