### ISSUE TITLE
Brainstorm: what config parameters do we need?

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#3]
To kick things off, I'll start with these. I've tried to sort them in a sort of chronological order:

- nickname for this configuration (so people can have several)
- download from bank (boolean)
- download from bank URL
- bank login
- bank auth1
- bank auth2
- downloaded file path (like "/home/username/Downloads/")
- downloaded filename pattern (like "bank_export_*")
- downloaded filename extension (like ".csv")
- downloaded file CSV delimiter character (like "," or ";")
- downloaded file has column headers (boolean)
- downloaded file column names and column order
- convert (boolean)
- converted file filename pattern (prefix like "fixed_")
- converted file filename pattern (suffix like "_fixed")
- converted filename extension (like ".csv")
- remove downloaded file after conversion (boolean)

**Comment by nocalla** [comment]
Nickname is a good idea. I suppose the script could try running each
nickname file in the folder if you had multiple accounts to sort at once. A
problem if the banks have different formats but the same names for the
files though.

On 10 Oct 2017 12:22, "Torben Gundtofte-Bruun" <notifications@github.com>
wrote:

To kick things off, I'll start with these:

   - nickname for this configuration (so people can have several)
   - downloaded file path (like "/home/username/Downloads/")
   - downloaded filename pattern (like "bank_export_*")
   - downloaded filename extension (like ".csv")
   - downloaded file CSV delimiter character (like "," or ";")
   - downloaded file column names and column order
   - downloaded file has column headers (boolean)
   - converted file filename pattern (prefix like "fixed_")
   - converted file filename pattern (suffix like "_fixed")
   - converted filename extension (like ".csv")

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/torbengb/bank2ynab/issues/3>, or mute the thread

**Comment by nocalla** [comment]
I'll make my file accept an external config so and we can see where to go from there.

**Comment by torbengb** [comment]
> Nickname

This is because my bank provides a bank statement and a credit-card transaction list; two files, two file names, two formats. Sigh. As for the file names, the "save" dialog that pops up when I press "download" contains a *suggestion* but I could just overwrite that with something else. Of course I'd prefer an idiot-proof method where I don't need to rename anything.

**Comment by nocalla** [comment]
Is it the same suggestion each time for filename?

**Comment by nocalla** [comment]
So your setup wouldn't cause a problem because you could set your search
pattern as something like bank_creditcard or bank_current account depending
on account.

**Comment by torbengb** [comment]
Exactly. It would be wonderful if the script could determine the content based on (part of) the filename --- or even based on the columns it finds, but that's a pipe dream.

**Comment by nocalla** [comment]
I question the logic of the "convert" boolean. Surely the point of the process is to get that converted file at the end?

**Comment by torbengb** [comment]
> question the logic of the "convert" boolean

You're correct. There's a toggle for download and a toggle for delete after conversion, so I figured I would list it for the sake of completeness. It should probably die.

**Comment by torbengb** [comment]
>  have the script look for all .conf files present in the script folder
Now THAT is clever! I love it!

**Comment by nocalla** [comment]
Struggling with git at the moment. Might commit some changes tomorrow.

**Comment by nocalla** [comment]
This is the sort of thing I'm envisioning. I'm currently reading the relevant documentation for the configparser module in Python which is how these files get read. Not sure if it makes more sense to have separate files or separate "sections" in one file for each "nickname".

```
# bank2ynab configuration file

[DEFAULT]
# Direct bank download
Bank Download = 0
Bank Download URL = ""
Bank Download Login = ""
Bank Download Auth1 = ""
Bank Download Auth2 = ""
# Filename search
Source Path = ""
Source Filename Pattern = "TransactionExport"
Source Filename Extension = ".csv"
# Source file formatting
Source CSV Delimiter = ","
Source Has Column Headers = 1
Input Columns = ["Date", "Payee", "Outflow", "Inflow", "Running Balance"]
# Output file formatting
Output Columns = ["Date", "Payee", "Category", "Memo", "Outflow", "Inflow"]
Output Filename Prefix = "fixed_"
Output Filename Extension = ".csv"
# Post-processing
Delete Source File = 1

[bank]
Output Filename Prefix = "alt_fixed_"
```

**Comment by torbengb** [comment]
Looks neat! But ... spaces in parameter names?

**Comment by nocalla** [comment]
Configparser allows it I think. It's just a mock-up for now, I haven't
experimented with reading from the file yet.

**Comment by nocalla** [comment]
Code pushed! Try it out!

**Comment by nocalla** [comment]
I've an active Pull Request that outlines config file support now.

**Comment by nocalla** [comment]
Just a quick note regarding the import format on the wiki - the script logs for column headers as they are named in YNAB, I.e.: Date, payee, category, memo, outflow, inflow. Input formats should be labelled this way (for the relevant columns anyway).

**Comment by torbengb** [comment]
I'll close this for now, as it appears we've pretty much covered the bases. Good work!!!
