### ISSUE TITLE
[Feature] template filename

### ISSUE THREAD

**Issue by toyg** [torbengb/bank2ynab#37]
This is a feature request, absolutely optional and not urgent, but there you go. 

It would be cool to actually put in some logic to allow for templates from source filenames. What I mean is:

- UK Cooperative bank (and Smile online bank) generate csv files called `XXXXXX_ZZZZZZZZ_YYYY_MM_DD.csv`, where `XXXXXX` is the bank sort code, `ZZZZZZZZ` is the account number, and `YYYY_MM_DD` is the date when the file was generated.

- it would be cool if bank2ynab could understand these info, even superficially. This would probably help in any future feature that involves automatic uploading, since it might make it easier to target this or that account.

**Comment by nocalla** [comment]
Thanks for the feedback. That's interesting - so there isn't a common
factor in the names of the files? Can you provide an example of a few
filenames? Change your account number etc, obviously!

**Comment by toyg** [comment]
An example filename looks like `123456_98765432_2017_10_21.csv`. 123456 is a six-digit ID (called "sort code") that identifies the UK bank; 98765432 is an 8-digit ID that identifies an account in that bank; and the rest is the date. The sort code / account number scheme is used by all banks across the uk and anyone with a bank account is familiar with it.

As it is, in order to use bank2ynab, I would set the source filename parameter to `123456_98765432_`, because that doesn't change across runs; but it might be useful for the script to actually understand what those numbers (and the date) are. So for example we could have config parameters like this:
```
Parsing Source Filename = true
Parsing Source Filename Template = uksort_ukaccount_yyyy_mm_dd.csv
```

As I said, totally optional at the moment, but might turn out useful down the line, because in this way the script can receive information about the account that is not in the file itself.

**Comment by nocalla** [comment]
Okay, thanks again for the feedback. Will definitely look at cleverer file
recognition.

**Comment by nocalla** [comment]
So, I've been looking into this and am at a bit of an impasse. 

I *think* it makes sense to do some kind of regex matching to find a filename. But is this the sort of thing that's better suited to a plugin file or should it be a general incorporation into the conf file? If it's a general thing, how best to "package" it in the conf file. Have a regex boolean in the conf file that causes the filename snippet to be interpreted as a regex? 

Or is regex even the right approach - would glob work better? I don't think so, because wildcards seem a bit awkward in glob, but I'm open to suggestions here, @toyg and @torbengb.

**Comment by nocalla** [comment]
I think glob would require the following for your example above, so think it should be regex alright! There's not a repeating character syntax for glob, just single character wildcards (that I can see anyway).
`files = glob.glob(join(path, "[0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9]_[0-9][0-9]_[0-9][0-9].csv"))`

**Comment by nocalla** [comment]
I've made a branch using regular expressions instead of the original file searching. I'd be grateful if you folks could give it a look over.
