### ISSUE TITLE
Separate default config file from users' actual configuration

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#49]
Situation:
Users (including ourselves) make changes to the `bank2ynab.conf` file, not least in order to specify our personal preference for the download directory.

Problem:  
Having a user-modified local config file conflicts with the config file of the package because it has the same name.

Solution suggestion:
We could deliver the config file as `bank2ynab.conf.txt` and require the user to actively rename or copy it to `bank2ynab.conf` in order to activate it. That would be part of the user guide / installation instructions and could also be checked by the suggested `validate()` function.   
This would allow us to maintain a true "package version" while allowing users to hold local preferences in their own actual copy. 

Drawback:  
When a user downloads an updated release, he must actively merge the changes in the new `bank2ynab.conf.txt` into his existing `bank2ynab.conf`. 

The drawmack carries a risk of mistakes, but the benefit of content separation could make it worth it. Thoughts?

**Comment by nocalla** [comment]
I would argue that it's better to have to update your own config manually. Means you only process the formats that you want. This prevents the accidental conversion of your file in another format which matches the search criteria, a problem that becomes more likely the more banks are added. I'm in favour of this. It also means we can "exclude" syncing the personal config file in git.

**Comment by torbengb** [comment]
I can't tell whether you agree with me or not? :) It sounds like it to me but you don't directly say so. 

I think you're saying that the user could copy the provided template (what I meant above) and then remove all the sections he doesn't care about to prevent unwanted section matches (a great idea).

So do you agree that we could/should rename `bank2ynab.conf` to `bank2ynab.conf.txt` and have the user create his own local copy of it? The user would then "have to update [his] own config manually" as you point out and I agree that seems to be the safest approach.

**Comment by nocalla** [comment]
I am uncertain about the .txt file. I think supply the files as they are
now, but also provide a myconfig.conf file which overrides the default if
it has anything in it. That way there's a backup if they don't customise
anything.

**Comment by jd1** [comment]
I only change the `Source Path` to the correct folder and leave the rest as it is. As a normal user I don't want to change the bank config.

But when I adjust the bank config, I don't want to commit my custom `Source Path`.

So there are two user of the config file:
* The "normal" end user, who only adjust the upper part of the file.
* The developers, who change the lower part with the bank config

There should be a way to make boths users happy. Possible options could be:
* Split the files into user properties and bank formats
* Allow the end user to create an extra config file to overwrite some properties.
* ...

**Comment by nocalla** [comment]
As stated above, I'm in favour of the extra config file approach. 

This option is also pretty much implemented - if a second .conf file is created in the directory with a [DEFAULT] section, as long as that file is read after the main config, it'll overwrite any parameters specified in the main one. 

The only thing to implement is to make sure the main config is read first, I think. Should be straightforward enough- just means hardcoding the filename.

**Comment by nocalla** [comment]
Current config logic = conf_files = [f for f in os.listdir(".") if f.endswith(".conf")]

This finds all configuration files in the directory. Files later in the list overwrite earlier files, so if there's a "Default" section in file 2, it'll overwrite file 1's defaults. 

The problem with this is that the order is arbitrary. So the solution is to hard-code the config names. I'm going with "bank2ynab.conf" and "user_configuration.conf". I have a pull request ready to merge. I'll leave it sit for a bit in case it causes problems.
