### ISSUE TITLE
We need a user guide

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#5]
- how to get the script working
  - how to install required modules
  - how to modify the config file
  - how the script detects one or more config files, and how it finds the correct config section
  - how to take advantage of the bank formats included in the project

(see https://github.com/torbengb/bank2ynab/pull/4#issuecomment-336991769 for a starting point)

**Comment by nocalla** [comment]
I think we can do a "package" in the files that carries the required modules in a portable way. I'll have to look into the best way to do that.

**Comment by torbengb** [comment]
> I'll have to look into the best way to do that.

Okay, assigned to you. I'll keep issue #15 for me to work on.

**Comment by nocalla** [comment]
I don't know what exactly we need to document for dependencies, to be honest. Just Python 3 really. You've got everything important covered in the user guide so far.

**Comment by torbengb** [comment]
You're right - back when I was using python2 I had to install the configparser (for v2), but when we switched the shebang to v3 the configparser (which is separate for v3) was already present. Close this ticket?

**Comment by nocalla** [comment]
Closing for now, might need to reopen when we look at 2.x compatibility.
