### ISSUE TITLE
Support for more complex formats

### ISSUE THREAD

**Issue by toyg** [torbengb/bank2ynab#53]
There is a question of how much we can actually stretch the current approach of just reordering a few fields. For example, I'm looking at https://github.com/JamesBelchamber/ynab-jlp-csv-converter/blob/master/convert.py and apparently that bank (JLP) does not have different columns for Inflows and Outflows, but rather a single column for values that are marked as CR in another field when it's a credit. This is literally the first random script I picked from the list, chances are that there are loads of these. Special-casing this sort of thing will only get us so far.

What about adding the possibility of loading a different class that will do the record parsing and will then provide an iterator returning the necessary format? That way we can deal with untractable special cases in dedicated modules.

I'm thinking we could have a modules subfolder that contains, for example, a jlp.py file with some sort of class that provides a standard interface. Then in the config file the user could specify an option like Parsing Module = jlp. If the option is specified, the code will load the module and hand over parsing to it, expecting to get back an iterator that we can use with csv; otherwise, we do the regular parsing (in fact, we could have a default.py module that holds default parsing logic, shortening the main script). This is pretty easy in Python 3 with a bit of importlib magic, and I'm pretty sure there is a Python2 equivalent too.

As well as dealing with difficult special cases, this could potentially open the door to supporting pretty much any file format, not just csv.

**Comment by nocalla** [comment]
My thinking is that we wouldn't need a module for each bank, as there'll be
a limited number of special cases, but rather we could end up saying jpl
fits module A while rabo fits module B etc.

**Comment by toyg** [comment]
> there'll be a limited number of special cases

You are an inveterate optimist ☺️

I agree that we won't need a module for every single bank; this would be more of a hatch for when the default approach of column reordering breaks down.

The idea of leaving the choice to the user is mostly to avoid the burden of reverse-detecting a bank, which would end up with a massive chain of `if`s in the main loop through sections; and leave the possibility of a user writing his own module without touching anything in the main script (which makes it easier to merge contributions). We can always provide a module name in the same way we provide bank-specific parameters for known banks at the moment.

**Comment by nocalla** [comment]
Agreed!

**Comment by toyg** [comment]
Laid the foundation for this in 9aef33a4f4f830f6d44dd04b00abe2e49ca0f656

**Comment by toyg** [comment]
Now that we have a working plugin, i think we can consider this resolved :)
