### ISSUE TITLE
Python 2: CSV not working with non-ascii characters

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#57]
As sourced from @toyg:
> Ok, I did some more testing and there is still an outstanding issue with csv not working properly in py2 when source data contains non-ascii characters, regardless of how source or target files are opened and regardless of unicode_literals (which I'd rather stay away from, anyway, since it changes a lot of things behind the scenes in py2).
> 
> This is even mentioned halfway through the examples, providing a solution (the UnicodeWriter class) that is fugly but will probably work. I'll have a look online for alternatives.

Prerequisite before sorting Pull #56

**Comment by toyg** [comment]
Done.
