### ISSUE TITLE
Python 3: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 21: invalid continuation byte

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#60]
Using a freshly downloaded bank file, I get this error with Python 3 (on `master` and also on the other branches). (discovered while testing #59)

```
Your specified download directory was not found: /home/torben/Downloadsx
Parsing file: elbi_umsaetze_20171025234336.csv
Using format: AT Raiffeisen Bank
Traceback (most recent call last):
  File "bank2ynab.py", line 179, in <module>
    main()
  File "bank2ynab.py", line 169, in main
    output = clean_data(file)
  File "bank2ynab.py", line 76, in clean_data
    for row in transaction_reader:
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 21: invalid continuation byte
```

Note:  

- The file seems to be not in Unicode format but in _Windows ISO-8859-1_ format, at least according to Notepadqq (a Notepad++ clone for Linux).  
- The VISA statement from the same bank, same website, same time of download, is reported as _UNIX/OS X UTF-8 w/o BOM_ format. This file has not been tested yet because the script stops after the first file (and I haven't tried to run it without the other file present yet!).

**Comment by nocalla** [comment]
Renamed for clarity. Python 3 isn't an issue!

**Comment by toyg** [comment]
Can you refresh the py2 branch and try again (executing with python3) ? I reworked the approach and I think it's more robust across both versions.

**Comment by nocalla** [comment]
I've accidentally merged py2 into master, so just refresh the master...I was trying to rebase py2 to master and messed up. Sorry if this completely breaks things, but @toyg had some great changes and I think it all looks good!

**Comment by torbengb** [comment]
# SUCCESS

I've just grabbed the current master again and tested using Py2 and Py3, and both work perfectly. I honestly can't think of anything more to break now! Given this, I am going to close this ticket. 

## GOOD JOB!!!
