### ISSUE TITLE
FileNotFoundError when trying to write output file where file doesn't exist yet

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#65]
python bank2ynab.py
Format: IE Bank of Ireland
Can't find: c:\users\example-username\Downloads
Trying: D:\Users\nocalla\Downloads
Parsing file: test_BOI_TransactionExport (2).csv
Parsed 28 lines
Writing file: fixed_test_BOI_TransactionExport (2).csv
Traceback (most recent call last):
  File "bank2ynab.py", line 341, in <module>
    main()
  File "bank2ynab.py", line 330, in main
    write_data(file, output)
  File "bank2ynab.py", line 280, in write_data
    with CrossversionCsvWriter(new_filename, __PY2) as writer:
  File "bank2ynab.py", line 44, in __init__
    self.encoding = detect_encoding(self.file_path)
  File "bank2ynab.py", line 110, in detect_encoding
    with codecs.open(filepath, "r", encoding=enc) as f:
  File "C:\Users\nocalla\AppData\Local\Programs\Python\Python35-32\lib\codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Users\\nocalla\\Downloads\\fixed_test_BOI_TransactionExport (2).csv'

**Comment by nocalla** [comment]
This looks like a problem with @toyg's CrossVersionCsvWriter, but I don't really understand how that function works so I don't know how to fix it! Works fine when the output filename already exists in the folder.

**Comment by nocalla** [comment]
It seems to be that we try to find the encoding of the output file, which we can't do because it doesn't exist.  Can we disable the self.encoding on line 44 if it's an output file?

**Comment by toyg** [comment]
This should be fixed now. I really need that testing stuff :)

**Comment by toyg** [comment]
For the record, I've also deleted the py2 branch since it had been fully merged. There are probably a bunch of issues here that can be closed.

**Comment by nocalla** [comment]
I can confirm issue is fixed on Windows.
