### ISSUE TITLE
Config file search pattern is too simple

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#74]
Situation:

- The check currently looks in the script directory for *any* file that `endswith(".conf")` ([line 156](https://github.com/torbengb/bank2ynab/blob/master/bank2ynab.py#L156)). What is the reason for this choice of search pattern?

Problem:

- No error appears if the actual `bank2ynab.conf` is missing, if `foo.conf` is present.
- The search pattern would also find a file named `foo.conf` or even one named `dont_use_this_bank2ynab.conf`.
- These files would be found even if the actual `bank2ynab.conf` is present. Which one would then be used?

Suggestion:  

- Search for the exact config file `bank2ynab.conf`.

**Comment by nocalla** [comment]
All conf files found in the script's folder are used together. This was to
allow multiple conf files when we were going to use a different one for
each bank.

**Comment by toyg** [comment]
Yeah I don’t think this is a problem, it’s actually a ConfigParser feature. It will probably come in handy when/if we start having dozens of banks and it makes sense to split them in their own conf files, to avoid making the main one unreadable.

Maybe we could have a bank2ynab.conf file that we actually check for, containing all necessary defaults to actually start; and then a “conf” subfolder with a
file per bank. This way the user can delete from there anything he wants and we can still start and show meaningful errors in all circumstances; and if we change our mind about loading everything indiscriminately, we can just add a directive in the main config file to load only this or that additional conf (e.g. “Enabled Banks = iob,raiff” would only load conf/iob.conf and conf/raiff.conf).

**Comment by nocalla** [comment]
I agree - this could be useful still. Having a standalone bank2ynab.conf could be useful for user-specific settings too.

**Comment by torbengb** [comment]
I like the way your thoughts are going! I want to withdraw this "bug". Should I just close it, or do we still need it for something?

**Comment by nocalla** [comment]
I think close it and we can revisit it under a different heading.

**Comment by torbengb** [comment]
Agree - closing.
