### ISSUE TITLE
chatgroup

### ISSUE THREAD

**Issue by toyg** [torbengb/bank2ynab#76]
I think it could be worth having a chatgroup somewhere to coordinate in realtime. Last night I was almost undone by not realizing @nocalla was pushing to the same branch I was working on.

I’m happy with anything you guys like - telegram, whatsapp, irc...

**Comment by torbengb** [comment]
Fine by me - prefer something web based if possible, and also I don't have Whatsapp but I do use Telegram, Signal, Slack, and probably more that I can't think of right now. Something IRC-like is probably useful.

**Comment by torbengb** [comment]
A quick Google search led me to gitter.im which is a dedicated chat service for GitHub users. I created a room and invited you guys: https://gitter.im/bank2ynab/Lobby
If you don't like it / prefer something else, that's fine by me too. This is just an experiment until we know how useful it is to us.

**Comment by nocalla** [comment]
The chatroom seems to work well and the integration with Github and Travis is very handy. Marking as closed.
