### ISSUE TITLE
[Optimisation] Bring existing code into line with PEP8

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#78]
The following issues were flagged in the main script by pycodestyle.py. It's probably worth looking at these for the purpose of readability as the code grows more complex. 
This is based off the test-prep branch as it stands currently (which I think needs to be merged into master, as I mentioned in #77.).
EDIT 2: Obviously we'll need to do this every now and then, but I've brought the existing code in the core up to standard anyway. Closing this.

EDIT: Worked through these, so moved them below this line.
- [x] bank2ynab.py:311:80: E501 line too long (102 > 79 characters)
- [x] bank2ynab.py:328:80: E501 line too long (99 > 79 characters)
- [x] bank2ynab.py:133:80: E501 line too long (86 > 79 characters)
- [x] bank2ynab.py:32:1: E402 module level import not at top of file
- [x] bank2ynab.py:33:1: E402 module level import not at top of file
- [x] bank2ynab.py:34:1: E402 module level import not at top of file
- [x] bank2ynab.py:35:1: E402 module level import not at top of file
- [x] bank2ynab.py:99:80: E501 line too long (85 > 79 characters)
- [x] bank2ynab.py:218:80: E501 line too long (93 > 79 characters)
- [x] bank2ynab.py:220:80: E501 line too long (98 > 79 characters)
- [x] bank2ynab.py:219:80: E501 line too long (101 > 79 characters)
- [x] bank2ynab.py:217:80: E501 line too long (92 > 79 characters)
- [x] bank2ynab.py:216:80: E501 line too long (86 > 79 characters)
- [x] bank2ynab.py:214:80: E501 line too long (95 > 79 characters)
- [x] bank2ynab.py:213:80: E501 line too long (97 > 79 characters)
- [x] bank2ynab.py:212:80: E501 line too long (95 > 79 characters)
- [x] bank2ynab.py:104:80: E501 line too long (113 > 79 characters)
- [x] bank2ynab.py:105:80: E501 line too long (119 > 79 characters)
- [x] bank2ynab.py:106:80: E501 line too long (115 > 79 characters)
- [x] bank2ynab.py:107:80: E501 line too long (115 > 79 characters)
- [x] bank2ynab.py:108:80: E501 line too long (116 > 79 characters)
- [x] bank2ynab.py:109:80: E501 line too long (112 > 79 characters)
- [x] bank2ynab.py:110:80: E501 line too long (115 > 79 characters)
- [x] bank2ynab.py:111:80: E501 line too long (119 > 79 characters)
- [x] bank2ynab.py:112:80: E501 line too long (112 > 79 characters)
- [x] bank2ynab.py:113:80: E501 line too long (117 > 79 characters)
- [x] bank2ynab.py:114:80: E501 line too long (104 > 79 characters)
- [x] bank2ynab.py:122:80: E501 line too long (86 > 79 characters)
- [x] bank2ynab.py:282:80: E501 line too long (141 > 79 characters)
- [x] bank2ynab.py:296:80: E501 line too long (99 > 79 characters)
- [x] bank2ynab.py:89:80: E501 line too long (81 > 79 characters)
- [x] bank2ynab.py:276:13: E722 do not use bare except'
- [x] bank2ynab.py:86:37: E128 continuation line under-indented for visual indent
- [x] bank2ynab.py:87:37: E128 continuation line under-indented for visual indent

**Comment by nocalla** [comment]
Dealing with the bare except - the exception returned is "Error: Input directory not found:" which doesn't seem to match any existing exceptions listed in the docs. Exploring this further.

**Comment by nocalla** [comment]
@toyg do we need to specify all the subclasses of ValueError in line 135 in the encoding brute forcing?
`except ValueError or UnicodeError or UnicodeDecodeError or UnicodeEncodeError:`
It [looks like](https://docs.python.org/2/library/exceptions.html) ValueError is the parent of all the others there, so wouldn't that be triggered if any of the children are raised?

**Comment by toyg** [comment]
In my initial tries it didn’t seem to catch it if I went only for
ValueError, but feel free to check... you could add a test that expects an
exception :)
