### ISSUE TITLE
newline = "" only works on Windows

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#8]
Line 111:

I've looked things up and it seems that the 'open()' call should be replaced with an 'io.open()' call instead. I believe the reason is that 'open()', on Linux, does not have the 'newline' parameter (not even in my up-to-date version '3.5.1-3').  ([source](https://stackoverflow.com/a/40492450/20571), [source](https://stackoverflow.com/q/33891373/20571))

Using 'io.open()' requires an import of 'io' in line 20, which in turn requires 'io' to have to be installed first using 'sudo python -m pip install unicodecsv').

But using 'io.open()' gives me all kinds of follow-up troubles, so that can't be it either. I also found sources that suggested importing 'unicodecsv' instead of 'csv' because that handles things nicer, but that too became too hairy for a Python novice as I am.

[Another suggestion](https://stackoverflow.com/a/29841468/20571)  (and [another](https://stackoverflow.com/a/3394898/20571)) was to code myself out of the parameter problem while staying with the normal 'open()' but I couldn't make it work:

    #    with open(new_filename, "w", newline = "") as file:
        if os.name is "nt": newlinefoo = {'newline':''}
        else: newlinefoo = {}
        with open(new_filename, "w", newlinefoo) as file:

**Comment by nocalla** [comment]
All these issues list using an older version of Python as a cause. Are you
*definitely* using an up-to-date Python?

**Comment by torbengb** [comment]
I am puzzled too, but my Linux installation insist that I do have version '3.5.1-3'.

**Comment by nocalla** [comment]
And are you definitely *running *using the Python 3 instance? Python 2 is
sometimes installed on systems and runs by default when you call Python.
What do you get on calling "python -V"?

**Comment by torbengb** [comment]
Closing this, as it appears my installation at fault, using Python 2.x when I should have used v3.
The shebang prevents this from reoccurring.
