### ISSUE TITLE
configparser.NoOptionError: No option 'plugin' in section: 'AT Raiffeisen Bank'

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#81]
Script language: Python2 and Python3
Operating system: Linux
OS Version: Ubuntu 16.04 LTS

What did you DO? (steps to reproduce)
grabbed bank2ynab.py from master, then ran it once with py2 and once with py3.

What did you EXPECT to happen?
successful conversion.

What ACTUALLY happened?
Error using py2: 

```
Traceback (most recent call last):
  File "bank2ynab.py", line 451, in <module>
    b2y = Bank2Ynab(get_configs(), __PY2)
  File "bank2ynab.py", line 423, in __init__
    bank_config = fix_conf_params(config_object, section)
  File "bank2ynab.py", line 231, in fix_conf_params
    config[key] = get_config_line(conf_obj, section_name, config[key])
  File "bank2ynab.py", line 245, in get_config_line
    line = conf_obj.get(section_name, param)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'plugin' in section: 'AT Raiffeisen Bank'
```

Error using py3:

Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/lib/python3.5/collections/__init__.py", line 878, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.5/collections/__init__.py", line 870, in __missing__
    raise KeyError(key)
KeyError: 'plugin'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "bank2ynab.py", line 451, in <module>
    b2y = Bank2Ynab(get_configs(), __PY2)
  File "bank2ynab.py", line 423, in __init__
    bank_config = fix_conf_params(config_object, section)
  File "bank2ynab.py", line 231, in fix_conf_params
    config[key] = get_config_line(conf_obj, section_name, config[key])
  File "bank2ynab.py", line 245, in get_config_line
    line = conf_obj.get(section_name, param)
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'plugin' in section: 'AT Raiffeisen Bank'
```

- I do not understand what the `option 'plugin'` means. There is no config parameter containing that word. 
- I also noted that the line `Use Payees for Memo` was removed from the default section in .conf in master. I would say that's a mistake and it should come back (default FALSE). Right?

**Comment by nocalla** [comment]
The use payee for memo line was intentionally removed a while back. It just
avoids empty memo fields.

**Comment by nocalla** [comment]
This error looks like the new Plugin field is missing from whatever config file is being used.

**Comment by toyg** [comment]
yeah it should be None by default. It's the field that allows for extensions.

**Comment by nocalla** [comment]
Duplicated in Windows. Definitely missing from .conf file. Will fix now.

**Comment by nocalla** [comment]
Inserted to the conf file, but still getting an error.
`Traceback (most recent call last):
  File "bank2ynab.py", line 449, in <module>
    b2y = Bank2Ynab(get_configs(), __PY2)
  File "bank2ynab.py", line 422, in __init__
    bank_object = build_bank(bank_config)
  File "bank2ynab.py", line 401, in build_bank
    p_mod = importlib.import_module(".{}".format(plugin_module), "plugins")
  File "C:\Users\Niall\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module 'plugins' not loaded, cannot perform relative import`

**Comment by nocalla** [comment]
Ah, the key is initialised in the dictionary as "plugin" but is searched for as "plugins". Remember my lesson learned yesterday about not pushing code that I hadn't tried to run? :-P

**Comment by torbengb** [comment]
Ah, I begin to understand how this is supposed to work - and once I understand it better, I would be happy to write the documentation for it. 

That would probably be too much to put in the *user guide* section of the *readme* file - if so then I will revive the wiki and have the readme link to it. I'll open an issue for this. 

I know Github also offers some kind of a documentation system and format based on SRT files rather than TXT or wiki, but that's another sub-project right there. 

- So should we move our five existing formats out of the conf file and into five sample plugins instead?

**Comment by nocalla** [comment]
I don't think we should split out the conf file. I think the plugins are specifically for projects requiring different parsing requirements, e.g.: that Japanese bank example where all inflow and outflow were in the same column and had another column indicating with a letter code whether they were debit or credit.

**Comment by torbengb** [comment]
Okay, we can use the plugins for particularly obnoxious cases and keep the config for the easy pickings.
That means we are providing (and supporting) two separate approaches, but with luck the plugin story will not get used much.

**Comment by toyg** [comment]
Yes, the idea is that plugins are a fallback for particular cases where the regular csv parser does not work. This should be stated clearly where the subject comes up.
