### ISSUE TITLE
Branching strategy?

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#88]
So far we (well, you!) have been very good and diligent about doing changes in feature-specific branches. (I haven't been as diligent, but luckily my inputs have been mostly testing and documentation so I don't feel too guilty.) 

Anyway, I've been thinking about terms like "versions" and "releases". As long as all our efforts flow back into `master`, I'm not sure we can ever say we have a stable release point?

You're probably aware of several different strategies. I happen to like [this one](http://nvie.com/posts/a-successful-git-branching-model/) and put it to you as a question: should we think about having a branching strategy? Which one? This one I suggested ([cheat sheet here](https://danielkummer.github.io/git-flow-cheatsheet/)), or some other?

**Comment by nocalla** [comment]
That makes sense to me. Though not so much having feature branches outside of origin. That's for larger scale projects I reckon. Go with git-flow. I'll install Sourcetree.

**Comment by torbengb** [comment]
> having feature branches outside of origin

I think that's what you have been doing for the most part already -- only merging back into `master` when you were more or less done with the code change?

I have now run the git-flow-init locally and I've also pushed the `develop` to GitHub now. 
Also, I have set that as the default branch -- please let me know if that causes problems!

I understand that `origin/develop` becomes our integration branch, and that's the one that Travis should be monitoring. 

- [ ] We still need to tell Travis to use `origin/develop` instead of `origin/master` as its [default branch](https://travis-ci.org/torbengb/bank2ynab/branches). I haven't found that setting yet.

**Comment by nocalla** [comment]
Outside of master, yes, but not outside of origin. I.e. I haven't been
developing on my own fork.

**Comment by nocalla** [comment]
Why do we need to tell Travis that `develop` is the default branch? Does it make a difference to Travis? He still checks all branches. Unless you're looking at auto-merging feature branches into `develop `when they're stable?

On another note - my suggestion is to follow your article and use a naming protocol for features. Sourcetree's default seems to be to use `feature/new-feature` as its naming protocol, so I suggest we follow that example for naming our branches. I just pushed [an example branch](https://github.com/torbengb/bank2ynab/tree/feature/date-parsing) (I haven't changed anything in it, just pushed a renamed `develop`).

**Comment by toyg** [comment]
Definitely a good idea to move development to a different trunk. For the rest I don't really care about branch naming, what is really important is that we remember to delete minor branches once merged.

**Comment by nocalla** [comment]
I think we've established a good branching strategy. Closing.
