### ISSUE TITLE
Support for Handelsbanken [SE]

### ISSUE THREAD

**Issue by joacand** [torbengb/bank2ynab#89]
Hi, I got a request from @toyg to add this issue here since you were looking for more formats with input examples to add to this project.

This is about support for Handelsbanken, a Swedish bank.

The file extension is .xls, but the content of the file is HTML. See attached file for input example. Note that the actual data is anonimised, so the math does not add up.

[kontotransactionlist.txt](https://github.com/torbengb/bank2ynab/files/1435166/kontotransactionlist.txt)
(The attached file has extension .txt since it's not allowed to attach .xls files on github, but the real file should be .xls)

Since the format is unconventional you will probably need a plugin. I created a converter some time ago which may help: https://github.com/joacand/HandelsbankenYNABConverter

It's just a quick script and it probably needs be improved and changed to fit this project. You are free to use the code in any way you see fit.

**Edit from Nocalla (tentative config 15/02/2018)**
[SE Handelsbanken]
Source Filename Pattern = kontotransactionlist
Source Filename Extension = .xls
Input Columns = skip,Date,Payee,Inflow,skip
Source CSV Delimiter = ;
Header Rows = 7
Plugin = handelsbanken

From Issue #21 master list

**Comment by nocalla** [comment]
Great! Thanks for the input. We'll have a look at the format and see what we can come up with!

**Comment by nocalla** [comment]
Working on this over in the branch here: [89_Handelsbanken_SE](https://github.com/torbengb/bank2ynab/tree/feature/%2389_Handelsbanken_SE). 

Essentially, I think the key thing to do is to pre-process the file to strip out the HTML, leaving a normal CSV file that our regular functions can act on. This allows for future-proofing to some extent, in case we want to change our read_data function in some way.
