### ISSUE TITLE
Support for Rabobank [NL]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#90]
Example row: "NL12RABO3456789012","EUR","20140318","D","3.00","","","20140318","ba","","Rest Bernoulliborg GRONINGEN","Betaalautomaat 14:42 pasnr. 004","","","","","","",""
Note date format.
- [Remco32/rabobank-to-ynab-converter](https://github.com/Remco32/rabobank-to-ynab-converter) Gives us column header example and row example!
- [BrianSetz/rabonab](https://github.com/BrianSetz/rabonab)
- [canassa/rabobank-ynab](https://github.com/canassa/rabobank-ynab) Lists filename as transactions.csv!
- [eddokloosterman/php-rabobank-ynab-csv-converter](https://github.com/eddokloosterman/php-rabobank-ynab-csv-converter) Lists filename as transactions.txt.
- [jtdev/ynab-converter](https://github.com/jtdev/ynab-converter) [java] This one lists transactions.csv AND transactions.txt!
- [karsalfrink/RabobankToYNAB](https://github.com/karsalfrink/RabobankToYNAB) [Python] transactions.txt again.

```
[NL Rabobank]
Source Filename Pattern = transactions
Source Filename Extension = .txt
Input Columns = skip,skip,Date,Outflow/Inflow Designator,Inflow,skip,Payee,skip,skip,skip,Memo,skip,skip,skip,skip,skip,skip,skip
Plugin = Need to parse the Outflow/Inflow designator. This is reasonably common, so a general plugin for this would probably be most helpful.
```

Master Issue #21

**Comment by BrianSetz** [comment]
Official description: https://www.rabobank.nl/images/formaatbeschrijving_csv_kommagescheiden_nieuw_29539176.pdf

Filename when downloaded is always "transactions.txt", it is comma separated. Each column is wrapped in double quotes ("for","example")

1# Owner's Account | 2# Currency | 3# Interest Date (YYYYMMDD) | 4# Withdraw (D) / Deposit (C) | 5# Amount | 6# Target Account | 7# Target Name | 8# Entry Date (YYYYMMDD) | 9# Type of Transaction (1 or 2 letters) | 10# Filler (unused?) | 11# Description | 12# Description | 13# Description | 14# Description | 15# Description | 16# Description | 17# SEPA Related | 18# SEPA Related | 19# SEPA Related
--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--
NL12RABO3456789012 | EUR | 20170101 | D | 12.34 | NL98RABO7654321098 | Name of target account holder | 20170102 | https://nl.wikipedia.org/wiki/Rekeningafschrift |  | This | is | a | very | long | description |

Apologies if some translations are a little wonky. 

Hope this helps, @torbengb

**Comment by nocalla** [comment]
Great, thanks @BrianSetz! I've updated the configuration template above based on your response. 

We'll need to do up a plugin to parse column 4 and apply it to column 5.

**Comment by torbengb** [comment]
Hi Nocalla! I had some spare time today and had a go at the plugin. Care to take a look? I'd love to know if I made any mistakes.

**Comment by nocalla** [comment]
I'll have a look later in the week. Thanks!
