### ISSUE TITLE
Support for ING [NL]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#91]
Header row: "\"Datum\",\"Naam / Omschrijving\",\"Rekening\",\"Tegenrekening\",\"Code\",\"Af Bij\",\"Bedrag (EUR)\",\"MutatieSoort\",\"Mededelingen\""
- [AndreSomers/ING2YNAB](https://github.com/AndreSomers/ING2YNAB) (empty project)
- [dive/ing-to-ynab-json-converter](https://github.com/dive/ing-to-ynab-json-converter) 
- [ernezt/ynab-ing-converter](https://github.com/ernezt/ynab-ing-converter)This doesnt' look like a real program...
- [Remco32/ing-to-ynab-converter](https://github.com/Remco32/ing-to-ynab-converter) I can't really interpret this one!

**Comment by nocalla** [comment]
Source Filename Pattern = ???
Source Filename Extension = ???
Use Regex for Filename = ???
Source CSV Delimiter = ,
Input Columns =  Date,\"Naam / Omschrijving\",\"Rekening\",\"Tegenrekening\",\"Code\",\"Af Bij\",\"Bedrag (EUR)\",\"MutatieSoort\",skip

I'm not having much luck parsing this one!

**Comment by torbengb** [comment]
The way, the header translates to:

    Date, Payee,"Account","Counter Account","Code","Location","On","Amount (EUR)","Change Type", Memo
([DeepL](https://www.deepl.com/translator) is much better than Google Translate.)

And looking into [the file](https://github.com/Remco32/ing-to-ynab-converter/blob/master/main.c) line 83ff:

    //Output order is different for credit and debet

I would say that line 84 seems to check a **credit/debit flag** (so we need a plugin!) and the following 12 lines then build the YNAB output by picking fields from the input in the sequence 0,1,8,6. The difference in the two blocks must be that c/d flag. So going by the commas it seems to build the output as:  

    if 5="A" then credit = 0,1,,8,,6  
    if 5="B" then debit  = 0,1,,8,6,  
Ergo we get this:  
Input Columns = Date,Payee,skip,skip,skip,**CDFlag**,Amount,skip,Memo

    [NL ING]
    Source Filename Pattern = ????
    Source Filename Extension = ????
    Use Regex for Filename = ????
    Source CSV Delimiter = ,
    Header Rows = 1
    Footer Rows = 0
    Input Columns = Date,Payee,skip,skip,skip,**CDFlag**,Amount,skip,Memo
    Plugin =nl-ing

I found the delimiter mentioned in a comment on line 70!

This was fun :)

**Comment by nocalla** [comment]
The credit-debit flag is coming up often enough that I think it needs
incorporation or a more general plugin.

**Comment by nocalla** [comment]
So, as a result of #161 we can propose the following format.
```
[NL ING]
Source Filename Pattern = ????
Header Rows = 1
Footer Rows = 0
Input Columns = Date,Payee,skip,skip,skip,CDFlag,Amount,skip,Memo
Inflow or Outflow Indicator = 5,A,B
```

More information needed to get the filename pattern, alas. I think assuming the other parameters match our default is safe enough.

**Comment by torbengb** [comment]
Updated the in-out indicator to reflect the entire field value as per [Kurt Stolle](https://github.com/kurt-stolle/ynab-ing-parser/issues/1#issuecomment-366990355):

```
[NL ING]
Source Filename Pattern = ????
Header Rows = 1
Footer Rows = 0
Input Columns = Date,Payee,skip,skip,skip,CDFlag,Amount,skip,Memo
Inflow or Outflow Indicator = 5,Af,Bij
```

Filename is still unresolved. Once we have that, the format can go into `bank2ynab.conf`.

**Comment by torbengb** [comment]
As per Kurt, "The default filename is the IBAN followed by range of dates that export covers. An export of 2018-02-05 until and including 2018-02-20 would have the format NLxxINGBxxxxxxxxx_05_02_2018_19_02_2018.csv where an 'x' denotes an integer value of in the IBAN." So I think we have this:

```
[NL ING]
Use Regex for Filename = True
Source Filename Pattern = NL[0-9]{2}INGB[0-9]{9}_[0-9]{2}_[0-9]{2}_[0-9]{4}_[0-9]{2}_[0-9]{2}_[0-9]{4}.csv
Header Rows = 1
Footer Rows = 0
Input Columns = Date,Payee,skip,skip,skip,CDFlag,Amount,skip,Memo
Date Format = YYYYMMDD
Inflow or Outflow Indicator = 5,Af,Bij
```

I'll add this to our config and test with the sample file linked above.

**Comment by torbengb** [comment]
Closed, because it's implemented. Re-open if testing fails.
