### ISSUE TITLE
Support for Nordea [DK,SE]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#92]
Sources:
- [bivainis/ynab-csv-nordea](https://github.com/bivainis/ynab-csv-nordea)
- [davols/nordea-ynab-convert](https://github.com/davols/nordea-ynab-convert)
- [cosminlupu/to-ynab](https://github.com/cosminlupu/to-ynab)

`2017-10-23,Kortköp 171019 GOG COM,,"-119,00","1.000,99"
`

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

**Comment by torbengb** [comment]
I've submitted [this question](https://github.com/bivainis/ynab-csv-nordea/issues/1) to bivainis/ynab-csv-nordea -- please note that's not NO (Norway) but actually DK (Denmark).

**Comment by nocalla** [comment]
So Nordea DK is supported now? Should we split off Nordea SE?

**Comment by torbengb** [comment]
I think we should prepare to have separate formats for Nordea NO, Nordea SE, Nordea DK.

**Comment by torbengb** [comment]
Closing this issue now because both DK and SE formats are in the config now. (NO is missing, but I don't think we have a source for that.)
